# Generated by Django 3.2 on 2022-04-22 20:11

import django.core.validators
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menu_image",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        force_format="JPEG",
                        keep_meta=False,
                        quality=80,
                        size=[400, 500],
                        upload_to="menu_images/",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "food_items",
                    models.CharField(
                        max_length=300,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[, a-zA-Z]*$",
                                "Enter comma separated items. (use space to seperate two-word items)",
                            )
                        ],
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Price")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
